### ISSUE TITLE
SDK 3.1 build and run issues

### ISSUE THREAD

**Issue by jferguson-gnubio** [gregoiresage/pebble-autoconfig#52]
Hi, I'm just starting with Pebble coding and pebble-autoconfig (embedded), and I have SDK 3.1.

I had problems building, and while I got my app to *build*, I get no response from the settings icon and nothing shows up via `pebble logs`.

My changes to get it to build were quite probably insufficient or incorrect, as I was groping in the dark a bit.  I tried to work out what your changes to wscript were and to make them to the 3.1 wscript, and I got things working with adding:
```
    ctx.load('autoconfig', tooldir='pebble-autoconfig/wtools')
```
to each function, and replacing `pbl_program` with `pbl_autoconfprogram`.

For my entire change to my app to add pebble-autoconfig (with wscript diffs from the 3.1 default), See https://github.com/WJCFerguson/pebble_fuzzy_plus/commit/b90e5412b8362a0210b159b090ba0da455308e02

I'm assuming I'm seeing problems because you haven't ported to SDK 3.1's wscript?  Or perhaps I just missed some other step?  If you can help, I'd really appreciate it.   Thanks.

**Comment by gregoiresage** [comment]
Hi,

thanks for using the project :-D

The line 47 of your wscript is not updated for pebble-autoconfig, it must be : 
ctx.pbl_bundle(binaries=binaries, js='pebble-js-app.js')

**Comment by jferguson-gnubio** [comment]
Thank you!  I'll try that out soon.

Well done filling this huge hole in Pebble's SDK.  I was dismayed when I
realized how difficult it would be for me to add basic settings.
 pebble-autoconfig to the rescue!
